"""Collect every run under results/ into docs/EXPERIMENTS.md and results/_summary/ plots."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import yaml

from utils.config import ROOT
from utils.logger import read_json

STRONG, TARGET = 0.21808, 0.37708


def collect():
    runs = []
    for d in sorted((ROOT / "results").iterdir()):
        if not (d / "config.yaml").exists():
            continue
        cfg = yaml.safe_load((d / "config.yaml").read_text())
        if cfg.get("stage") == "smoke":
            continue
        status = "done" if (d / "DONE").exists() else "FAILED" if (d / "FAILED").exists() else "running/pending"
        variants = {p.parent.name[5:]: read_json(p) for p in sorted(d.glob("eval_*/metrics.json"))}
        runs.append(dict(id=d.name, cfg=cfg, status=status, m=read_json(d / "metrics.json"),
                         t=read_json(d / "train_summary.json", {}), variants=variants))
    return runs


def f(v, nd=4):
    return "–" if v is None else f"{v:.{nd}f}"


def main():
    kaggle = yaml.safe_load((ROOT / "docs" / "kaggle_scores.yaml").read_text()) or {}
    runs = collect()
    by_id = {r["id"]: r for r in runs}
    lines = [
        "# Experiments",
        "",
        "Generated by `scripts/summarize.py`; do not edit by hand. All scores are local validation",
        "mAP50:95 computed from the Kaggle-format CSV with the TA's torchmetrics call.",
        f"Strong baseline {STRONG}, score to beat {TARGET}.",
        "",
        "| id | stage | model | imgsz | epochs | change | parent | mAP50:95 | Kaggle | Δ parent | mAP50 | mAP75 | mAP small | weakest 3 classes | train h | peak VRAM GB | status |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in runs:
        c, m, t = r["cfg"], r["m"], r["t"]
        model = Path(c["model"].get("arch") or c["model"].get("weights") or c["model"].get("name", "?")).stem
        parent = c.get("parent")
        pm = by_id.get(parent, {}).get("m") if parent else None
        delta = f"{m['map'] - pm['map']:+.4f}" if m and pm else "–"
        weak = ", ".join(f"{k} {v:.2f}" for k, v in sorted(m["per_class"].items(), key=lambda kv: kv[1])[:3]) if m else "–"
        lines.append(
            f"| {r['id']} | {c.get('stage')} | {model} | {c['train']['imgsz']} | {c['train']['epochs']} | {c.get('notes', '')} | {parent or '–'} | "
            f"{f(m and m['map'])} | {f(kaggle.get(r['id']), 5)} | {delta} | {f(m and m['map_50'])} | {f(m and m['map_75'])} | {f(m and m['map_small'])} | {weak} | "
            f"{f(t.get('train_hours'), 2)} | {f(t.get('peak_vram_gb_train'), 1)} | {r['status']} |"
        )
    var_rows = [(r, tag, v) for r in runs for tag, v in r["variants"].items()]
    if var_rows:
        lines += ["", "## Inference variants (same weights, different inference settings)", "",
                  "| id | variant | mAP50:95 | Kaggle | Δ default | mAP50 | mAP small | s / image | peak VRAM GB |", "|---|---|---|---|---|---|---|---|---|"]
        for r, tag, v in var_rows:
            delta = f"{v['map'] - r['m']['map']:+.4f}" if r["m"] else "–"
            lines.append(f"| {r['id']} | {tag} | {v['map']:.4f} | {f(kaggle.get(f"{r['id']}/eval_{tag}"), 5)} | {delta} | {v['map_50']:.4f} | {v['map_small']:.4f} | {v['sec_per_image']} | {v['peak_vram_gb_infer']} |")
    scored = [r for r in runs if r["m"]]
    if scored:
        best = max(scored, key=lambda r: r["m"]["map"])
        lines += ["", f"Best single default-inference run: **{best['id']}** at {best['m']['map']:.4f}."]
        lines += ["", "## Per-class AP", "", "| id | " + " | ".join(best["m"]["per_class"]) + " |", "|---|" + "---|" * len(best["m"]["per_class"])]
        for r in scored:
            lines.append(f"| {r['id']} | " + " | ".join(f"{v:.3f}" for v in r["m"]["per_class"].values()) + " |")
    (ROOT / "docs" / "EXPERIMENTS.md").write_text("\n".join(lines) + "\n")

    if scored:
        out = ROOT / "results" / "_summary"
        out.mkdir(exist_ok=True)
        fig, ax = plt.subplots(figsize=(max(6, 0.9 * len(scored)), 4))
        bars = ax.bar([r["id"] for r in scored], [r["m"]["map"] for r in scored], color="#4477aa")
        ax.bar_label(bars, fmt="%.3f", fontsize=8)
        ax.axhline(STRONG, color="#888", ls="--", lw=1)
        ax.text(-0.4, STRONG, " strong baseline", va="bottom", fontsize=8, color="#555")
        ax.axhline(TARGET, color="#cc3311", ls="--", lw=1)
        ax.text(-0.4, TARGET, " score to beat", va="bottom", fontsize=8, color="#cc3311")
        ax.set_ylabel("val mAP50:95")
        plt.xticks(rotation=40, ha="right")
        fig.tight_layout()
        fig.savefig(out / "val_map.png", dpi=130)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
